drop policy "Users can insert weight for their pets" on "public"."weight";

drop policy "Users can read their pets weight" on "public"."weight";


  create table "public"."food" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "description" text,
    "quantity" character varying
      );


alter table "public"."food" enable row level security;


  create table "public"."pets_food" (
    "pet_id" bigint not null,
    "food_id" bigint not null
      );


alter table "public"."pets_food" enable row level security;

CREATE UNIQUE INDEX food_pkey ON public.food USING btree (id);

CREATE UNIQUE INDEX pets_food_pkey ON public.pets_food USING btree (pet_id, food_id);

alter table "public"."food" add constraint "food_pkey" PRIMARY KEY using index "food_pkey";

alter table "public"."pets_food" add constraint "pets_food_pkey" PRIMARY KEY using index "pets_food_pkey";

alter table "public"."pets_food" add constraint "pets_food_food_id_fkey" FOREIGN KEY (food_id) REFERENCES public.food(id) not valid;

alter table "public"."pets_food" validate constraint "pets_food_food_id_fkey";

alter table "public"."pets_food" add constraint "pets_food_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES public.pets(id) not valid;

alter table "public"."pets_food" validate constraint "pets_food_pet_id_fkey";

grant delete on table "public"."food" to "anon";

grant insert on table "public"."food" to "anon";

grant references on table "public"."food" to "anon";

grant select on table "public"."food" to "anon";

grant trigger on table "public"."food" to "anon";

grant truncate on table "public"."food" to "anon";

grant update on table "public"."food" to "anon";

grant delete on table "public"."food" to "authenticated";

grant insert on table "public"."food" to "authenticated";

grant references on table "public"."food" to "authenticated";

grant select on table "public"."food" to "authenticated";

grant trigger on table "public"."food" to "authenticated";

grant truncate on table "public"."food" to "authenticated";

grant update on table "public"."food" to "authenticated";

grant delete on table "public"."food" to "service_role";

grant insert on table "public"."food" to "service_role";

grant references on table "public"."food" to "service_role";

grant select on table "public"."food" to "service_role";

grant trigger on table "public"."food" to "service_role";

grant truncate on table "public"."food" to "service_role";

grant update on table "public"."food" to "service_role";

grant delete on table "public"."pets_food" to "anon";

grant insert on table "public"."pets_food" to "anon";

grant references on table "public"."pets_food" to "anon";

grant select on table "public"."pets_food" to "anon";

grant trigger on table "public"."pets_food" to "anon";

grant truncate on table "public"."pets_food" to "anon";

grant update on table "public"."pets_food" to "anon";

grant delete on table "public"."pets_food" to "authenticated";

grant insert on table "public"."pets_food" to "authenticated";

grant references on table "public"."pets_food" to "authenticated";

grant select on table "public"."pets_food" to "authenticated";

grant trigger on table "public"."pets_food" to "authenticated";

grant truncate on table "public"."pets_food" to "authenticated";

grant update on table "public"."pets_food" to "authenticated";

grant delete on table "public"."pets_food" to "service_role";

grant insert on table "public"."pets_food" to "service_role";

grant references on table "public"."pets_food" to "service_role";

grant select on table "public"."pets_food" to "service_role";

grant trigger on table "public"."pets_food" to "service_role";

grant truncate on table "public"."pets_food" to "service_role";

grant update on table "public"."pets_food" to "service_role";


  create policy "Anyone can insert weights "
  on "public"."weight"
  as permissive
  for insert
  to public
with check (true);



  create policy "Users can read their pets weight"
  on "public"."weight"
  as permissive
  for select
  to public
using (true);



