
  create table "public"."reminder" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "description" text,
    "timestamp" timestamp with time zone not null,
    "repeat_rule" text not null,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."reminder" enable row level security;

CREATE UNIQUE INDEX reminder_pkey ON public.reminder USING btree (id);

alter table "public"."reminder" add constraint "reminder_pkey" PRIMARY KEY using index "reminder_pkey";

alter table "public"."reminder" add constraint "reminder_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."reminder" validate constraint "reminder_user_id_fkey";

grant delete on table "public"."reminder" to "anon";

grant insert on table "public"."reminder" to "anon";

grant references on table "public"."reminder" to "anon";

grant select on table "public"."reminder" to "anon";

grant trigger on table "public"."reminder" to "anon";

grant truncate on table "public"."reminder" to "anon";

grant update on table "public"."reminder" to "anon";

grant delete on table "public"."reminder" to "authenticated";

grant insert on table "public"."reminder" to "authenticated";

grant references on table "public"."reminder" to "authenticated";

grant select on table "public"."reminder" to "authenticated";

grant trigger on table "public"."reminder" to "authenticated";

grant truncate on table "public"."reminder" to "authenticated";

grant update on table "public"."reminder" to "authenticated";

grant delete on table "public"."reminder" to "service_role";

grant insert on table "public"."reminder" to "service_role";

grant references on table "public"."reminder" to "service_role";

grant select on table "public"."reminder" to "service_role";

grant trigger on table "public"."reminder" to "service_role";

grant truncate on table "public"."reminder" to "service_role";

grant update on table "public"."reminder" to "service_role";


  create policy "Enable delete for users based on user_id"
  on "public"."reminder"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."reminder"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable update for users based on user_id"
  on "public"."reminder"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Users can read their reminders"
  on "public"."reminder"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable update for users based on user_id"
  on "public"."user_information"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = auth_user_id))
with check ((( SELECT auth.uid() AS uid) = auth_user_id));



