


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."medication" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "description" "text",
    "quantity" "text" NOT NULL
);


ALTER TABLE "public"."medication" OWNER TO "postgres";


COMMENT ON TABLE "public"."medication" IS 'Table with Information about Medication for pet';



ALTER TABLE "public"."medication" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Medication_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "birthdate" "date" NOT NULL,
    "description" "text",
    "type" character varying NOT NULL,
    "owner_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."pets" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets" IS 'Table with Pet Information';



ALTER TABLE "public"."pets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Pets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "pictures" "text",
    "user_id" "uuid"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."profiles" IS 'Table of Profiles for Users';



ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_information" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "auth_user_id" "uuid" NOT NULL,
    "phonenumber" character varying,
    "email" character varying
);


ALTER TABLE "public"."user_information" OWNER TO "postgres";


COMMENT ON TABLE "public"."user_information" IS 'Table with User Information';



ALTER TABLE "public"."user_information" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."vaccins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "type" character varying,
    "shot_date" "date",
    "expire_date" "date"
);


ALTER TABLE "public"."vaccins" OWNER TO "postgres";


COMMENT ON TABLE "public"."vaccins" IS 'Table with information about Vaccins';



ALTER TABLE "public"."vaccins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Vaccins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."weight" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" "text" NOT NULL,
    "date" "date" NOT NULL
);


ALTER TABLE "public"."weight" OWNER TO "postgres";


COMMENT ON TABLE "public"."weight" IS 'Table of Weights of certain pet';



ALTER TABLE "public"."weight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Weight_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pets_medication" (
    "pet_id" bigint NOT NULL,
    "medication_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_medication" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_medication" IS 'Link pet to medication';



CREATE TABLE IF NOT EXISTS "public"."pets_vaccin" (
    "pet_id" bigint NOT NULL,
    "vaccin_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_vaccin" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_vaccin" IS 'Link pet to vaccin';



CREATE TABLE IF NOT EXISTS "public"."pets_weight" (
    "pet_id" bigint NOT NULL,
    "weight_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_weight" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_weight" IS 'Link weight to pet';



ALTER TABLE ONLY "public"."medication"
    ADD CONSTRAINT "Medication_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "Pets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "Profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_information"
    ADD CONSTRAINT "User Information_auth_user_id_key" UNIQUE ("auth_user_id");



ALTER TABLE ONLY "public"."user_information"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."vaccins"
    ADD CONSTRAINT "Vaccins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."weight"
    ADD CONSTRAINT "Weight_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_pkey" PRIMARY KEY ("pet_id", "medication_id");



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_pkey" PRIMARY KEY ("pet_id", "vaccin_id");



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_pkey" PRIMARY KEY ("pet_id", "weight_id");



ALTER TABLE ONLY "public"."user_information"
    ADD CONSTRAINT "User Information_auth_user_id_fkey" FOREIGN KEY ("auth_user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_medication_id_fkey" FOREIGN KEY ("medication_id") REFERENCES "public"."medication"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets"
    ADD CONSTRAINT "pets_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_vaccin_id_fkey" FOREIGN KEY ("vaccin_id") REFERENCES "public"."vaccins"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_weight_id_fkey" FOREIGN KEY ("weight_id") REFERENCES "public"."weight"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user_information"("auth_user_id");



CREATE POLICY "Users can delete medication links for their pets" ON "public"."pets_medication" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_medication"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their pets medication" ON "public"."medication" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_medication" "pm"
     JOIN "public"."pets" "p" ON (("pm"."pet_id" = "p"."id")))
  WHERE (("pm"."medication_id" = "medication"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their pets vaccinations" ON "public"."vaccins" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_vaccin" "pv"
     JOIN "public"."pets" "p" ON (("pv"."pet_id" = "p"."id")))
  WHERE (("pv"."vaccin_id" = "vaccins"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their pets weight" ON "public"."weight" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_weight" "pw"
     JOIN "public"."pets" "p" ON (("pw"."pet_id" = "p"."id")))
  WHERE (("pw"."weight_id" = "weight"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete vaccination links for their pets" ON "public"."pets_vaccin" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_vaccin"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete weight links for their pets" ON "public"."pets_weight" FOR DELETE USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_weight"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert medication for their pets" ON "public"."medication" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."pets_medication" "pm"
     JOIN "public"."pets" "p" ON (("pm"."pet_id" = "p"."id")))
  WHERE (("pm"."medication_id" = "medication"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert medication links for their pets" ON "public"."pets_medication" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_medication"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert their pets" ON "public"."pets" FOR INSERT WITH CHECK (("auth"."uid"() = "owner_id"));



CREATE POLICY "Users can insert vaccination links for their pets" ON "public"."pets_vaccin" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_vaccin"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert vaccinations for their pets" ON "public"."vaccins" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."pets_vaccin" "pv"
     JOIN "public"."pets" "p" ON (("pv"."pet_id" = "p"."id")))
  WHERE (("pv"."vaccin_id" = "vaccins"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert weight for their pets" ON "public"."weight" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."pets_weight" "pw"
     JOIN "public"."pets" "p" ON (("pw"."pet_id" = "p"."id")))
  WHERE (("pw"."weight_id" = "weight"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can insert weight links for their pets" ON "public"."pets_weight" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_weight"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets" ON "public"."pets" FOR SELECT USING (("auth"."uid"() = "owner_id"));



CREATE POLICY "Users can read their pets medication" ON "public"."medication" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_medication" "pm"
     JOIN "public"."pets" "p" ON (("pm"."pet_id" = "p"."id")))
  WHERE (("pm"."medication_id" = "medication"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets medication links" ON "public"."pets_medication" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_medication"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets vaccination links" ON "public"."pets_vaccin" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_vaccin"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets vaccinations" ON "public"."vaccins" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_vaccin" "pv"
     JOIN "public"."pets" "p" ON (("pv"."pet_id" = "p"."id")))
  WHERE (("pv"."vaccin_id" = "vaccins"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets weight" ON "public"."weight" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_weight" "pw"
     JOIN "public"."pets" "p" ON (("pw"."pet_id" = "p"."id")))
  WHERE (("pw"."weight_id" = "weight"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can read their pets weight links" ON "public"."pets_weight" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM "public"."pets"
  WHERE (("pets"."id" = "pets_weight"."pet_id") AND ("pets"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can update their pets medication" ON "public"."medication" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_medication" "pm"
     JOIN "public"."pets" "p" ON (("pm"."pet_id" = "p"."id")))
  WHERE (("pm"."medication_id" = "medication"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can update their pets vaccinations" ON "public"."vaccins" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_vaccin" "pv"
     JOIN "public"."pets" "p" ON (("pv"."pet_id" = "p"."id")))
  WHERE (("pv"."vaccin_id" = "vaccins"."id") AND ("p"."owner_id" = "auth"."uid"())))));



CREATE POLICY "Users can update their pets weight" ON "public"."weight" FOR UPDATE USING ((EXISTS ( SELECT 1
   FROM ("public"."pets_weight" "pw"
     JOIN "public"."pets" "p" ON (("pw"."pet_id" = "p"."id")))
  WHERE (("pw"."weight_id" = "weight"."id") AND ("p"."owner_id" = "auth"."uid"())))));



ALTER TABLE "public"."medication" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_medication" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_vaccin" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_weight" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_information" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."vaccins" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."weight" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."medication" TO "anon";
GRANT ALL ON TABLE "public"."medication" TO "authenticated";
GRANT ALL ON TABLE "public"."medication" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pets" TO "anon";
GRANT ALL ON TABLE "public"."pets" TO "authenticated";
GRANT ALL ON TABLE "public"."pets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_information" TO "anon";
GRANT ALL ON TABLE "public"."user_information" TO "authenticated";
GRANT ALL ON TABLE "public"."user_information" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vaccins" TO "anon";
GRANT ALL ON TABLE "public"."vaccins" TO "authenticated";
GRANT ALL ON TABLE "public"."vaccins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."weight" TO "anon";
GRANT ALL ON TABLE "public"."weight" TO "authenticated";
GRANT ALL ON TABLE "public"."weight" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pets_medication" TO "anon";
GRANT ALL ON TABLE "public"."pets_medication" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_medication" TO "service_role";



GRANT ALL ON TABLE "public"."pets_vaccin" TO "anon";
GRANT ALL ON TABLE "public"."pets_vaccin" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_vaccin" TO "service_role";



GRANT ALL ON TABLE "public"."pets_weight" TO "anon";
GRANT ALL ON TABLE "public"."pets_weight" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_weight" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


