


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Medication" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "description" "text",
    "quantity" "text" NOT NULL
);


ALTER TABLE "public"."Medication" OWNER TO "postgres";


COMMENT ON TABLE "public"."Medication" IS 'Table with Information about Medication for pet';



ALTER TABLE "public"."Medication" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Medication_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Pets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying DEFAULT ''::character varying NOT NULL,
    "birthdate" "date" NOT NULL,
    "description" "text",
    "type" character varying NOT NULL,
    "owner_id" bigint NOT NULL
);


ALTER TABLE "public"."Pets" OWNER TO "postgres";


COMMENT ON TABLE "public"."Pets" IS 'Table with Pet Information';



ALTER TABLE "public"."Pets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Pets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Profiles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" bigint NOT NULL,
    "pictures" "text"
);


ALTER TABLE "public"."Profiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."Profiles" IS 'Table of Profiles for Users';



ALTER TABLE "public"."Profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User Information" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL
);


ALTER TABLE "public"."User Information" OWNER TO "postgres";


COMMENT ON TABLE "public"."User Information" IS 'Table with User Information';



ALTER TABLE "public"."User Information" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Vaccins" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "type" character varying,
    "shot_date" "date",
    "expire_date" "date"
);


ALTER TABLE "public"."Vaccins" OWNER TO "postgres";


COMMENT ON TABLE "public"."Vaccins" IS 'Table with information about Vaccins';



ALTER TABLE "public"."Vaccins" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Vaccins_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Weight" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" "text" NOT NULL,
    "date" "date" NOT NULL
);


ALTER TABLE "public"."Weight" OWNER TO "postgres";


COMMENT ON TABLE "public"."Weight" IS 'Table of Weights of certain pet';



ALTER TABLE "public"."Weight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Weight_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."pets_medication" (
    "pet_id" bigint NOT NULL,
    "medication_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_medication" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_medication" IS 'Link pet to medication';



CREATE TABLE IF NOT EXISTS "public"."pets_vaccin" (
    "pet_id" bigint NOT NULL,
    "vaccin_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_vaccin" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_vaccin" IS 'Link pet to vaccin';



CREATE TABLE IF NOT EXISTS "public"."pets_weight" (
    "pet_id" bigint NOT NULL,
    "weight_id" bigint NOT NULL
);


ALTER TABLE "public"."pets_weight" OWNER TO "postgres";


COMMENT ON TABLE "public"."pets_weight" IS 'Link weight to pet';



ALTER TABLE ONLY "public"."Medication"
    ADD CONSTRAINT "Medication_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Pets"
    ADD CONSTRAINT "Pets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Profiles"
    ADD CONSTRAINT "Profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User Information"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Vaccins"
    ADD CONSTRAINT "Vaccins_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Weight"
    ADD CONSTRAINT "Weight_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_pkey" PRIMARY KEY ("pet_id", "medication_id");



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_pkey" PRIMARY KEY ("pet_id", "vaccin_id");



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_pkey" PRIMARY KEY ("pet_id", "weight_id");



ALTER TABLE ONLY "public"."Pets"
    ADD CONSTRAINT "Pets_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."User Information"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Profiles"
    ADD CONSTRAINT "Profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."User Information"("id");



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_medication_id_fkey" FOREIGN KEY ("medication_id") REFERENCES "public"."Medication"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_medication"
    ADD CONSTRAINT "pets_medication_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."Pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."Pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_vaccin"
    ADD CONSTRAINT "pets_vaccin_vaccin_id_fkey" FOREIGN KEY ("vaccin_id") REFERENCES "public"."Vaccins"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_pet_id_fkey" FOREIGN KEY ("pet_id") REFERENCES "public"."Pets"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pets_weight"
    ADD CONSTRAINT "pets_weight_weight_id_fkey" FOREIGN KEY ("weight_id") REFERENCES "public"."Weight"("id") ON DELETE CASCADE;



ALTER TABLE "public"."Medication" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Pets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."User Information" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Vaccins" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Weight" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_medication" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_vaccin" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pets_weight" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Medication" TO "anon";
GRANT ALL ON TABLE "public"."Medication" TO "authenticated";
GRANT ALL ON TABLE "public"."Medication" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Medication_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Pets" TO "anon";
GRANT ALL ON TABLE "public"."Pets" TO "authenticated";
GRANT ALL ON TABLE "public"."Pets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Pets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Profiles" TO "anon";
GRANT ALL ON TABLE "public"."Profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."Profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Profiles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."User Information" TO "anon";
GRANT ALL ON TABLE "public"."User Information" TO "authenticated";
GRANT ALL ON TABLE "public"."User Information" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Vaccins" TO "anon";
GRANT ALL ON TABLE "public"."Vaccins" TO "authenticated";
GRANT ALL ON TABLE "public"."Vaccins" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Vaccins_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Weight" TO "anon";
GRANT ALL ON TABLE "public"."Weight" TO "authenticated";
GRANT ALL ON TABLE "public"."Weight" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Weight_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."pets_medication" TO "anon";
GRANT ALL ON TABLE "public"."pets_medication" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_medication" TO "service_role";



GRANT ALL ON TABLE "public"."pets_vaccin" TO "anon";
GRANT ALL ON TABLE "public"."pets_vaccin" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_vaccin" TO "service_role";



GRANT ALL ON TABLE "public"."pets_weight" TO "anon";
GRANT ALL ON TABLE "public"."pets_weight" TO "authenticated";
GRANT ALL ON TABLE "public"."pets_weight" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


